name: Deploy Backend to VPS

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    name: Deploy on VPS Runner
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd /root/EPO_Projects
          git pull origin main

      - name: Install dependencies
        run: |
          cd /root/EPO_Projects
          npm install --omit=dev

      - name: Restart PM2
        run: |
          export PATH=$PATH:/usr/local/bin
          pm2 restart backend-api
          pm2 status backend-api